npct/pct-shiny

master/pct-shiny-funs.R

@Robinlovelace Tested on Liverpool, showing fine for:  Lines | Centroids  |  Route network (f&q), no crashes.
I didn't commit or close issue yet, I will keep an eye on it. 
Thanks @usr110

Car% added to route network too

---

master/pct-shiny-funs.R

Label amended in lines & centroids.

'Car users %' (label) > '% who drive' (label)

---

master/pct-shiny-funs.R

Popup update

---

pct-shiny-funs.R

@Robinlovelace   Changes following James preferences on wording and info shown. Tested yesterday with latest Bedforshire data, no issues seen.
Still pretty sure still a bit more can be added re e.g. route types, so I won't close the issue yet.

Labels consistency and info shown per scenario

---

scripts/init.R

Note: this will only show a warning in the R
console and not in the UI. Closes #156

Do not forcefully checkout data

---

pct-shiny-funs.R
server-base.R

@Robinlovelace  Latest changes on labels consistency +use of kable. 
Pls notice that the data on intrazonal flows is not shown, so some values will appear as NA for now.

Labels consistency & use of kable

---

pct-shiny-funs.R

The £ sign causes issues, safer to use the unicode point (sadly).

Tidy labels

---

www/stylesheet.css

This looks ok on my Firefox but debain do strange things to it so might not look good on yours.  I want to get it looking good but tbh faffing with select boxes because FF native versions are ugly is a bit of a pain.  
Ref #157

Improve FF select

---

server-base.R

Remove the zone popups when any lines are shown

---

static/Manual.html

Hi Robin & Nikolai - I've made a start, renamed it the user manual and changed the intro text. Could you update?
It would also be really helpful to have the separate FAQs (which will be changed to chapters) separately editable as the amount of html on one page is making my head hurt. Is it possible to create separate sections for the different chapters and have this page call them? Thanks and let me know if I'm doing this wrong :)

Update and rename FAQs.html to Manual.html

---

server-base.R
ui-base.R

Rename show zones

---

server-base.R
ui-base.R

Order lines / flows by different variables

---

server-base.R

Closes #262 
This was a bit more complex than I'd hoped.  If your happy then merge away.

Make centers size vary with zoom

---

pct-shiny-funs.R
server-base.R
ui-base.R

This is not ready yet but the idea being for the server to generate the download files.  Could be done in a background thread.
The code joins routes and lines but we agreed to not do so I'll remove that.

Download on fly

---

server-base.R

All trips tidy

---

Server.md
server-base.R

Use codebook for route download

---

regions_www/m/server.R

Very basic demonstration of region change based on mouse click.
Issues are 
1. The popup obscures the mouse click (e.g. sometimes you click on the popup which doesn't change the region instead of the background which does)
2. The region name is lower case and not pretty
3. (Nice to have) feedback that the region change is happening, esp for large regions which take a second or two to load.
All these are fixable but I'd like general feedback first.

535 allow user to confirm region change

---

pct-shiny-funs.R
regions_www/m/server.R

Instead of adding highlighted region (polygons) on the fly, add all the regions in the start. 
Covers:
- Simplifies the code
- Highlighting is quicker
- Does not show any highlighted region when the mouse is over the already selected region
Needs to do:
- Set the view of the map when the app starts
- Further testing

Highlight polygons using leaflet library

---

pct-shiny-funs.R
regions_www/m/server.R

@Robinlovelace would appreciate it you test it.

Exclude current region from being highlighted when flows are displayed

---

regions_www/index.html
regions_www/la-map.html
regions_www/m/server.R

Planning to accept this PR around 15:00 today unless I hear back from @nikolai-b and @usr110 that there are any tech issues.
Heads up @AnnaGoodman1 @RachelAldred @JDWoodcock this is a 'bug fix' update.

Update production with fixed base-maps

---

regions_www/index.html
regions_www/m/ui.R
regions_www/tabs/about.html
regions_www/tabs/manual.html
regions_www/www/licence.html

I don't think we are producing a foreign language version so I'm removing locizify
This reverts commit 57c7fb3b8a6f485c92e01f3507a7b8da9d5e65d2.

Revert "Add locizify"

---

regions_www/www/stylesheet.css

Fixes #618
Looks like the table class got renamed, update the CSS

Fix stats table missing styling

---

regions_www/m/server.R

I think this may work as a fix for https://github.com/npct/pct-shiny/issues/626 , but please check! I can't see anything else breaking, but a paranoid it might...

attempt to restore centroids

---

regions_www/www/assets/extra.js

This was lost in the merge commit 62694c3
Fixes #623

Re hide banner

---

regions_www/m/server.R
regions_www/m/ui.R

see https://github.com/npct/pct-shiny/issues/629 for details

Fix sort by heat

---

non_www/tabs/download_national.html
non_www/tabs/download_region.html

warning users about the 'csv download of firefox' issue

temporary fix for https://github.com/npct/pct-shiny/issues/621

---

regions_www/www/assets/google-analytics.js

To comply with
https://www.gov.uk/service-manual/measuring-success/choosing-digital-analytics-tools#information-security-and-privacy
using
https://support.google.com/analytics/answer/2763052?hl=en

Anonymize IP in analytics

---

regions_www/m/server.R
regions_www/m/ui.R
regions_www/www/stylesheet.css

Needs feedback and tweaking but something like has been asked for a while.
Fixes #639

Add loading spinner

---

Server.md

Remove unsed deps

---

regions_www/www/assets/extra.js

Change page title when region changes

---

regions_www/m/server.R

On a subdirectory on the tileserver
Closes #647

Add Welsh LSOA tiles

---

regions_www/m/server.R

update url, as referenced here https://github.com/npct/pct-shiny/issues/661

fix IMD url

---

regions_www/m/pct_shiny_funs.R
regions_www/m/server.R

Pct schools last fixes

---

regions_www/m/pct_shiny_funs.R

Seems to be working fine. See here:
https://github.com/npct/pct-shiny/issues/681

Remove percentage info for smaller values

---

regions_www/m/server.R
regions_www/m/ui.R
regions_www/www/stylesheet.css

| Before  |  After |
|:-:|:-:|
|  ![old](https://user-images.githubusercontent.com/6289830/53839011-51b17100-3f8e-11e9-8388-f9f50bcb54fb.png) | ![new_ui](https://user-images.githubusercontent.com/6289830/53839025-5c6c0600-3f8e-11e9-83e8-826617141c65.png) |
| **Zoomed Before**| **Zoomed After** |
| ![screenshot-2019-3-5 propensity to cycle tool - lancashire](https://user-images.githubusercontent.com/6289830/53839045-6beb4f00-3f8e-11e9-8333-0f44f043051c.png) | ![screenshot-2019-3-5 propensity to cycle tool - lancashire 1](https://user-images.githubusercontent.com/6289830/53839049-71489980-3f8e-11e9-8cbb-f4e69f7cf091.png) |

UI improvment

---

regions_www/m/server.R

This is in reference to the issue created here: https://github.com/npct/pct-shiny/issues/705
@Robinlovelace, are you up to test it first, and then merge?
I think it would be wise to merge to `master` and then `prod` afterwards. What do you think?

Make all trips option available (whereever the data exists) for non-prod branches

---

regions_www/m/server.R

The new commute tiles are ready. For simplicity I've set the school
tiles v2 to point to the old school tiles till school v2 are ready.

New LSOA tiles

---

regions_www/www/front_page/map.js

:wave: you code works fine @usr110 but I think we can do this a bit cleaner, WDYT?
Also can we go back to making Pull requests please?  I know I've recently pushed to master but I think it is much better if we always get a review.

Near market map

---

regions_www/www/front_page/map.js

Census 2011 != 2011 Census
Fixes #717
> Sorry @nikolai-b should have done more testing of your PR
It is a minor bug and was my fault for leaving another place where names can be defined.  I don't think we need to apologise for bugs in code (or failing to spot them) :laughing:

Define the layer names once

---

regions_www/www/front_page/map.js

Use the https://api.jquery.com/attribute-starts-with-selector/ so we select the correct radio buttons
Fixes #729

Fix disabling controls

---

regions_www/index.html
regions_www/www/front_page/map.js

The blog is accessible on the [test-server](http://npct0.vs.mythic-beasts.com/)
Would you please approve this to update the live server @AnnaGoodman1

Update prod for the near market blog

---

regions_www/m/server.R

Limit loaded regions by size

---

Server.md
scripts/deploy-shiny
scripts/shiny-control
scripts/shiny-server.conf
scripts/shiny-server.service

Fixes #742 
This adds most of the scripts that are on the prod server but moves them inside this git repo to allow us to change them on deploy.  I've tested this marginally but will need to monitor the next deployments carefully.

Deployment update

---

regions_www/m/server.R

Need to use single [ or we get `attempt to select less than one element in integerOneIndex`
Need to also remove the element from loaded_data_accessed

[HOTFIX] Fix removing loaded objects

---

regions_www/m/pct_shiny_funs.R
regions_www/m/server.R

Should fix https://github.com/npct/pct-shiny/issues/759#issuecomment-512853445

Round null

---

regions_www/m/pct_shiny_funs.R
regions_www/m/server.R

I've commented in the code but this is easy to reproduce the crash:
* select Schools, Go Cambridge and Route Network (Clickable)
* select Commute
* Shiny dies :skull:

Cambridge crash

---

regions_www/m/pct_shiny_funs.R

As the description says. Relevant issue: #775.

Use slc instead of sivalue_heat for route_network. Fix #775

---

regions_www/licence.html

This was stopping GitHub pages from building

Remove broken link

---

regions_www/tabs/manual_body.html

From approved PR https://github.com/npct/pct-shiny/pull/831

Robinlovelace patch 1

---

scripts/deploy.sh

We can see that there was a network issue
https://app.circleci.com/pipelines/github/npct/pct-shiny/23/workflows/04ed181d-ec88-48c4-951e-0a1958ca51b4/jobs/1477/parallel-runs/0/steps/0-102
but the job is marked as succeeding.  I've triggered it again and it seems fine but I'm also updating the deploy script so it will retry until it succeeds.

Deploy improvements

---

jekyll-static/Gemfile
jekyll-static/Gemfile.lock

I removed these as I forgot we had windows devs, sorry @usr110 !

Add gems for Windows

---

Server.md
scripts/le-renew-haproxy

I update the crontab for another project and realised that the SSL infrastructure was undocumented so adding this incase something goes wrong.

Update server instructions

---

regions_www/index.html
regions_www/manual.html
regions_www/manual_body.html

small edits requested by James, to update news feed and make it more obvious that the manuals page includes reports too

210528 manual page edit

---

regions_www/accessibility.html

minor changes to text of accessibility statement, following DfT feedback. Please could you merge in and push to live server soon, @nikolai-b or @usr110 , since the DfT contact asked us to let him know when published? thanks

update accessibility statement in line with DfT comments

---

Server.md
scripts/deploy.sh
scripts/le-renew-haproxy
scripts/post-update
scripts/publish-pct-shiny
scripts/update-server

Update deployment and server docs
